### ISSUE TITLE
Well Fed & Medicated buffs get cancelled/removed before crafting

### ISSUE THREAD

**Issue by krisbartlettnz** [Junie-774/CraftingList#13] opened 2023-02-05 01:53 UTC
whenever macro is specified to use food and/or medication pot, plugin uses food and pot but cancels out the well fed buff right after applying it

is this intended or a bug?

love the plugin btw, good luck on top prog ^^

edit, vod if need: https://streamable.com/dkab9v

**Comment by Junie-774** [comment] 2023-02-05 15:43
Well, uhm, if the macro specifies some food is needed, it'd be counterproductive for the intended behavior to be to click it off xD.
I'll look into it, may come back here asking for more info if I can't reproduce it.
and thanks! You too :P

**Comment by Junie-774** [comment] 2023-02-05 15:56
Update I can't reproduce it. Any chance you could show me what appears in your /xllog with the log level set to 'Debug', starting from when you hit the craft button? Either a screenshot or a similar vod would work ^^

**Comment by Iondite** [comment] 2023-02-05 20:24
I have a similar issue here is my log
[Verbose console.txt](https://github.com/Junie-774/CraftingList/files/10612078/Verbose.console.txt)

**Comment by Iondite** [comment] 2023-02-05 20:31
it seems to reapply food twice but cancels it instead

**Comment by Junie-774** [comment] 2023-02-05 20:32
oh whoopsy it was a lil goof

The status name string for food and medicine got swapped in one spot in the code, so when it went to change the food, it would click off "medicated", and when it went to change the medicine, it'd click off "Well Fed"

feex soon

**Comment by krisbartlettnz** [comment] 2023-02-05 21:09
ah

**Comment by krisbartlettnz** [comment] 2023-02-05 21:10
whoops - my mistake (newbie at github)

yeah that seems to be the exact issue, let me know if you need the log still

**Comment by Junie-774** [comment] 2023-02-05 21:45
nw lolol. Update pushed, should be fixed, feel free to reopen if the problem continues

**Closed as completed by Junie-774** 2023-02-05 21:45 UTC
